<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="BCT-LTP-138" name="SeleniumDay15_DependsOnMethod.SoftAssertionDemo" tests="1" failures="0" timestamp="10 Aug 2022 14:05:09 GMT" time="10.867" errors="1">
  <testcase name="verifyLogin" time="10.867" classname="SeleniumDay15_DependsOnMethod.SoftAssertionDemo">
    <error type="java.lang.AssertionError" message="The following asserts failed:
	expected [file:///C:/Selenium/OfflineWebsiteForSelenium/OfflineWebsite/pages/examples/dashboard12.html] but found [file:///C:/Selenium/OfflineWebsiteForSelenium/OfflineWebsite/pages/examples/dashboard.html]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [file:///C:/Selenium/OfflineWebsiteForSelenium/OfflineWebsite/pages/examples/dashboard12.html] but found [file:///C:/Selenium/OfflineWebsiteForSelenium/OfflineWebsite/pages/examples/dashboard.html]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
	at SeleniumDay15_DependsOnMethod.SoftAssertionDemo.verifyLogin(SoftAssertionDemo.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- verifyLogin -->
</testsuite> <!-- SeleniumDay15_DependsOnMethod.SoftAssertionDemo -->
